apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}-config-envs
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
data:
  # Database Configs
  {{- if .Values.postgresql.enabled }}
  ICEBERG_REST__PG_HOST_R: {{ printf "%s.%s.svc.%s" (include "iceberg-catalog.postgresql.fullname" .) (.Release.Namespace) (.Values.clusterDomain) | b64enc | quote }}
  ICEBERG_REST__PG_HOST_W: {{ printf "%s.%s.svc.%s" (include "iceberg-catalog.postgresql.fullname" .) (.Release.Namespace) (.Values.clusterDomain) | b64enc | quote }}
  ICEBERG_REST__PG_PORT: {{ "5432" | b64enc | quote }}
  {{- else }}
  ICEBERG_REST__PG_HOST_R: {{ .Values.externalDatabase.host_read | toString | b64enc | quote }}
  ICEBERG_REST__PG_HOST_W: {{ .Values.externalDatabase.host_write | toString | b64enc | quote }}
  ICEBERG_REST__PG_PORT: {{ .Values.externalDatabase.port | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgresql.enabled }}
  ICEBERG_REST__PG_DATABASE: {{ .Values.postgresql.auth.database | toString | b64enc | quote }}
  {{- else }}
  ICEBERG_REST__PG_DATABASE: {{ .Values.externalDatabase.database | toString | b64enc | quote }}
  {{- end }}

  {{- if not .Values.postgresql.enabled }}
  {{- if not .Values.externalDatabase.userSecret }}
  ICEBERG_REST__PG_USER: {{ .Values.externalDatabase.user | toString | b64enc | quote }}
  {{- end }}
  {{- if not .Values.externalDatabase.passwordSecret }}
  ICEBERG_REST__PG_PASSWORD: {{ .Values.externalDatabase.password | toString | b64enc | quote }}
  {{- end }}
  {{- end }}

  # Auth Configs
  {{- if .Values.auth.oauth2.provider_uri }}
  ICEBERG_REST__OPENID_PROVIDER_URI: {{ .Values.auth.oauth2.provider_uri | toString | b64enc | quote }}
  {{- if .Values.auth.oauth2.client_id }}
  ICEBERG_REST__OPENID_CLIENT_ID: {{ .Values.auth.oauth2.client_id | toString | b64enc | quote }}
  {{- end }}
  {{- end }}

  # User Configs
  {{- range $k, $v := .Values.catalog.config }}
  {{ $k | quote }}: {{ $v | toString | b64enc | quote }}
  {{- end }}